# Generated by Django 4.0.1 on 2022-02-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_owner_alter_book_readers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BAD'), (2, 'NOT BAD'), (3, 'GOOD'), (4, 'NICE'), (5, 'AMAZING')], null=True),
        ),
    ]
