# Generated by Django 4.0.1 on 2022-02-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_userbookrelation_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255, verbose_name='Название книги')),
        ),
    ]
